enlaces:
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa
  card1:
    title: AEE SPAIN CHAPTER
    href: http://www.aeespain.org/aee-spain-charter/
    tags: 
      - Eficiencia
      - Certificados
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa
  card0:
    title: Directiva 2012/27/UE relativa a la eficiencia energética
    href: https://eur-lex.europa.eu/legal-content/ES/ALL/?uri=CELEX%3A32012L0027
    src: 
    tags: 
      - Eficiencia
      - Normativa

linksblogs:
  card0:
    title: CNMC
    href: https://blog.cnmc.es/
    src: https://www.cnmc.es/sites/default/files/CNMC_Logotipo.png
  card1:
    title: Greenpeace
    href: https://es.greenpeace.org/es/que-puedes-hacer-tu/consumo/ahorro-energia/
    src: https://es.greenpeace.org/es/wp-content/themes/gp/assets/images/greenpeace-logo-verde.svg
  card2:
    title: IDAE
    href: https://laenergiadeluzia.es/
    src: https://www.idae.es/profiles/idae/themes/idae_static/logo.png
  card3:
    title: NASA
    href: https://climate.nasa.gov/blog/
    src: https://www.nasa.gov/sites/all/themes/custom/nasatwo/images/nasa-logo.svg
  card4:
    title: EERE
    href: https://www.energy.gov/eere/about-us/eere-blog
    src: https://www.energy.gov/sites/all/themes/clean_energy/images/logo_seal.png
  card5:
    title: UNE
    href: https://revista.une.org/
    src: https://revista.une.org/images/une_logo.png
  card6:
    title: ashrae
    href: https://spain-ashrae.org/blog/
    src: https://spain-ashrae.org/wp-content/uploads/logos.jpg
  card7:
    title: ree
    href: https://www.ree.es/es/blog-entrelineas
    src: https://upload.wikimedia.org/wikipedia/commons/5/5f/Red_El%C3%A9ctrica_logo.svg
  card8:
    title: energystar
    href: https://www.energystar.gov/
    src: https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Energy_Star_logo.svg/1024px-Energy_Star_logo.svg.png

blogs:
  card1:
    id: exampleModal
    img: static/img/2020-12-15_20-46.png
    img1: static/img/2020-12-15_20-46.png
    title: Bajar la potencia contratada
    text: Si, finalmente, llegas a la conclusión de que tienes contratada más potencia de la que necesitas, puedes solicitar a tu compañía una disminución de los Kw contratados. De hecho, existen unas potencias normalizadas, dependiendo del Interruptor del Control de Potencia que tengamos.
    text1: Lo primero que hay que comprobar es que la instalación eléctrica es correcta y está vigente. Si todo es correcto, puedes solicitar el cambio a tu empresa eléctrica.La empresa tiene 5 días (desde que lo pides) para que entre en vigor la nueva potencia contratada. Si en 5 días no se ha tramitado la solicitud, la compañía deberá compensarte con 30€. La empresa tiene un plazo máximo de 15 días (desde que lo pides) para que entre en vigor la nueva potencia contratada.Al bajar la potencia el distribuidor le cambiará el ICP para adecuarlo a la nueva potencia. Esta gestión te costará 9,044760€ + IVA.El cuadro muestra las potencias disponibles para los contratos de la tarifa de último recurso (TUR). Dentro de ese menú podemos elegir la potencia que se ajuste a nuestras necesidades.
    text2: Flexibilizar la potencia contratada      La potencia contratada es la potencia máxima que se puede consumir de forma simultánea. Dicho de otra manera, es la capacidad que tenemos de conectar a la vez varios aparatos sin que “salten los plomos”. Si esto sucede, es que la potencia que tenemos contratada es inferior a nuestras necesidades. Pero, en general, la situación suele ser la contraria, la potencia que contratamos es superior a la que realmente necesitamos.
    text3: Reducir esa potencia que tenemos contratada es el consejo número 1 para intentar reducir nuestra factura. Otra de las medidas que introdujo el Real Decreto-ley es la flexibilización de la potencia contratada, ya no hay escalones y el consumidor puede contratar la potencia en múltiplos de 0,1 kW (es decir, puedes pasar de 4,6 kW a 4,5 kW, 4,4 kW, 4,3 kW etc. A modo de ejemplo, bajar la potencia por ejemplo, 0,5 kW tiene unos ahorros anuales de unos 26 euros (impuestos incluidos).
    href: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/
    href1: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/

  card2:
    id: exampleModaljiji
    img: static/img/2020-12-15_20-28.png
    img1: static/img/2020-12-15_20-46.png
    title: BAJAR EL IMPACTO MEDIOAMBIENTAL DE MI CONSUMO
    text:  Compruebe al final de su factura y contemple la posibilidad de cambiar de compañía eléctrica, ademas de ser una gestión que puede implicar un importante ahorro económico en la factura de la luz. El cliente puede considerar que paga demasiado, lo que le impulsa a buscar nuevas ofertas en el mercado de electricidad y realizar un traspaso a otra empresa energética.
    text1: En la CNMC hemos explicado cómo un consumidor puede ahorrar si opta por contratar la tarifa con discriminación horaria (¿recuerdas nuestro podcast?). Pues bien, igual no te has fijado en tu factura pero las comercializadoras de referencia -aquellas autorizadas para ofrecer la tarifa regulada, el Precio Voluntario al Pequeño Consumidor (PVPC)- están obligadas a informar en su factura a los consumidores con tarifa PVPC de qué ahorros obtendrían con el cambio a una tarifa con discriminación horaria (con la que se paga menos por la electricidad consumida entre 22:00 y las 12:00 del día siguiente en invierno y las 23:00 y las 13:00 del día siguiente en verano).
    text2: Está demostrado que, en la mayoría de los casos, tener contratada la tarifa con discriminación horaria implica un ahorro porque los peajes son significativamente más baratos en el periodo valle. Por cierto, debes saber que el trámite de cambio de tarifa (o de potencia) tiene un coste para el consumidor de unos 9 euros+IVA aunque en la CNMC hemos expresado nuestra disconformidad puesto que este cambio no requiere una traslado de operario al domicilio.
    text3:
    href: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/
    href1: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/

  card3:
    id: exampleModal3
    img: static/img/2020-12-15_20-50.png
    img1: static/img/2020-12-15_20-50.png
    title: El proceso de cambio de suministrador de electricidad o gas
    text:  Consultar los comercializadores. Cualquier consumidor puede elegir libremente el comercializador con el que desea contratar.
    text1:  Comparar y contactar con el comercializador elegido.  Puede comparar las ofertas de los comercializadores en el comparador de ofertas de energía de la CNMC comparadorofertasenergia.cnmc.es
        Tenga en cuenta, antes de un cambio, la existencia de cláusulas de preaviso o de cancelación anticipada con su comercializador anterior. Además del precio, atienda a otros aspectos importantes plazos de vigencia del contrato, servicios adicionales (urgencias, mantenimiento, reparaciones, etc.)
    text2: Está demostrado que, en la mayoría de los casos, tener contratada la tarifa con discriminación horaria implica un ahorro porque los peajes son significativamente más baratos en el periodo valle. Por cierto, debes saber que el trámite de cambio de tarifa (o de potencia) tiene un coste para el consumidor de unos 9 euros+IVA aunque en la CNMC hemos expresado nuestra disconformidad puesto que este cambio no requiere una traslado de operario al domicilio.
    text3: Dar el consentimiento y contratar
      Tras contactar con el comercializador debe dar el consentimiento y realizar la contratación.
      En el caso de contratación a distancia (telefónica, por internet, mediante visita a domicilio, etc.) dispone de un periodo de 14 días tras la contratación en el que puede desistir del contrato.
    href: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/
    href1: https://blog.cnmc.es/2013/11/04/consejos-para-reducir-la-factura-de-la-luz-i/

  card4:
    id: exampleModal4
    img: static/img/2020-12-15_20-44.png
    img1: static/img/2020-12-15_20-44.png
    title: Bajar el consumo de Energia Reactiva
    href: https://energysave.abb-drives.com/

  card5:
    id: exampleModal5
    img: static/img/2020-12-19_01-56.png
    img1: static/img/2020-12-19_01-56.png
    title: EFCIENCIA EN MOTORES ELECTRICOS
    href: https://energysave.abb-drives.com/



estudios_tecnicos:
  card1:
    img: static/2021-02-07_12-27.png
    title: Perdidas por orientacion
    text: fasdfasd
    href: https://airpgwszid.execute-api.eu-west-1.amazonaws.com/dev
  card2:
    img: static/2021-02-06_16-50.png
    title: Perdidas por sombra
    text: fasdfasd
    href: https://b9spctvcwj.execute-api.eu-west-1.amazonaws.com/dev
  card3:
    img: static/2021-02-07_12-27.png
    title: base
    text: fasdfasd
    href: https://airpgwszid.execute-api.eu-west-1.amazonaws.com/dev
  card4:
    img: static/2021-02-07_12-27.png
    title: basexls
    text: fasdfasd
    href: https://airpgwszid.execute-api.eu-west-1.amazonaws.com/dev
auditorias:
  auditoria1:
    title: Preliminar Gratuito
    href: https://8rbi2doorj.execute-api.eu-west-1.amazonaws.com/dev
  auditoria2:
    title: ashrae1
    href: https://8rbi2doorj.execute-api.eu-west-1.amazonaws.com/dev

solares:
  card1:
    img: static/2021-02-07_12-27.png
    title: Residencial_Unifamiliar
    text: fasdfasd
    href: https://5d010n1nwb.execute-api.eu-west-1.amazonaws.com/dev
  card2:
    img: static/2021-02-06_16-50.png
    title: Industrial
    text: fasdfasd
    href: https://lgudfpwpa4.execute-api.eu-west-1.amazonaws.com/dev
  card3:
    img: static/2021-02-07_12-27.png
    title: Agro_Riego
    text: fasdfasd
    href: https://bwdvraa92c.execute-api.eu-west-1.amazonaws.com/dev
  card4:
    img: static/2021-02-07_12-27.png
    title: Ganadero
    text: fasdfasd
    href: https://b9spctvcwj.execute-api.eu-west-1.amazonaws.com/dev
